### ISSUE TITLE
Survival Games - Teleporting problems.

### ISSUE THREAD

**Issue by Mauro2424** [MCGamerNetwork/Issues#539]
Just as the game is about to begin and player are about to be teleported to the map that has been voted for the bug happens.
Some player get instantly put as a spectators and some stay in the lobby and some actually go where they are supposted to go, in the map that has been voted for.
Even when deathmatch starts the players who have been stuck from the beginning will be stuck in the lobby. The game teleports them the lobby again and the player who have been teleported correctly start the deathmatch normally.

Video: https://www.youtube.com/watch?v=vi1bRQXyIOA

**Comment by subv3rsion** [comment]
Unfortunately, it looks like the logs for that specific server have been reset as of a recent maintenance in EU, so I cannot look up what happened on the server side.
Are you still experiencing this issue, and if so, can you provide me with a server ID, time, and date as listed in the sidebar?

**Comment by subv3rsion** [comment]
Without further information, due to the fact that we don't have those older server logs, we cannot proceed with this bug report. If you're still experiencing this issue, feel free to open a new issue, and please include the screenshot of the game, or the game's region, server ID, time, etc. as you did before, that way we can look up the logs appropriately.
