### ISSUE TITLE
Weird hack-looking hits

### ISSUE THREAD

**Issue by xPugPvPx** [MCGamerNetwork/Issues#584]
On MCSG, I recently have seen myself and others get very far hits on different maps. I have no hacks, and I tested this glitch on other servers and it has no affect. I have been accused of hacking and I would like to help this bug be defeated because I fear I will get banned. I have found this on: Holiday Resort, Solar Frost, Chernobyl, Valleyside, Zone 85, Zone 85 revamped, Lobby Games, Alaskan Village, and some of the newer maps. Please help me out, and I will try to get more footage of what is going on. I got told a lot that I was going to get banned for, 'Macros. ff, more reach' and I was told by a Doner Quantum that he was going to ban me for the servers fault, not mine. If I was to abuse this glitch, then fair enough, but im not playing mcsg because of it. It started when I did /deghost and ever since then it has been giving me incredible ranged hits.

**Comment by subv3rsion** [comment]
This should be resolved as of March 3rd, or somewhere around that date.
The problem was with an update to Spigot that caused hit detection to be a bit... off. Needless to say, as soon as our team was available, this was resolved.

Quantums do not have the power to ban, and unless you're doing something wrong, you have nothing to worry about regarding getting banned.
