### ISSUE TITLE
Map bug

### ISSUE THREAD

**Issue by RetroxMC** [MCGamerNetwork/Issues#590]
http://www.mediafire.com/download/r57cyhkaskqnq1r/photos.zip

**Comment by subv3rsion** [comment]
Please open a new issue here on GitHub using the reporting template shown here: https://github.com/MCGamerNetwork/Issues/blob/master/README.md
Otherwise, your issue, due to lack of detail and providing images on a third-party site, may not be accounted for.

In addition, please upload the images directly to the GitHub issue.
