### ISSUE TITLE
I get randomly banned for a "cheating client"

### ISSUE THREAD

**Issue by ItzTrox** [MCGamerNetwork/Issues#615]
im using forge 1.8 and i cant join the server. It says Xime Anti-Cheat: Detected use of a cheating client, and i get banned for 1 min. plz help

**Comment by subv3rsion** [comment]
In that case, you should stop using mods on our servers. :)

You're allowed to use OptiFine and other related *permitted* mods to the game. Whatever you're using in your Forge client is *NOT* permitted.

For more information, see our rules here: http://www.mcgamer.net/threads/mcgamer-updated-rules-version-3-0.12254/
Also, this is not a bug. This issue is now closed.
