### ISSUE TITLE
Spectator Visibility

### ISSUE THREAD

**Issue by sontate72** [MCGamerNetwork/Issues#632]
Yes, once again, some spectators are visible. Here's Giver's video showing it in deathmatch: https://www.youtube.com/watch?v=PZnaoWo4Bg0

**Comment by subv3rsion** [comment]
This issue has been closed due to failure to follow the [README](https://github.com/MCGamerNetwork/Issues/blob/master/README.md).
We are also not going to hunt down the evidence in a 12 minute video. If you're going to submit a bug report, please follow the [README](https://github.com/MCGamerNetwork/Issues/blob/master/README.md), which explains that you should provide as much detail as possible. This includes providing the video URL and time in said video.
