### ISSUE TITLE
Spectator Glitch

### ISSUE THREAD

**Issue by josh155** [MCGamerNetwork/Issues#668]
The newest update has made it so when you die and go in spectator you are no longer hidden. This used to happen before but not on a large scale. Virtually everyone who dies now is no longer hidden and can be very distracting as you don't know straight away whether it's a spectator or a player.

**Comment by HDMadSkillz** [comment]
It makes it hard for use to get evidence for people who are hacking as well

**Comment by Ceroria** [comment]
To replicate this, simply join an already in progress Survival Games match.  Not only will you be able to see your own character, but ingame players will be able to see you as well.  Spectators can now interfere with fights by blocking the view of others and moderators have a harder time catching hackers since hackers will see the moderator spectating.

**Comment by arsenalfcgunners** [comment]
This has been fixed I think.

**Comment by forairan** [comment]
This should be fixed as of the next deployment cycle. It only happened in a specific case, where the SG server was previously a hub.
Thanks for the report!
