### ISSUE TITLE
ZedChase solo servers

### ISSUE THREAD

**Issue by vanicle** [MCGamerNetwork/Issues#689]
Gametype: ZedChase

Issue: King of the Hill [solo] gamemode does not exist. Even when it has 100% of the votes, it will still place you in a King of the Hill [team] game. http://i.imgur.com/nvGZifO.jpg

In Capture the Flag [solo], most people died at the top while they were falling down since you are able to hit any of the players. We started in about a 11 person game and before we fell to the platform, there were only 3 players still alive because they were all killed immediately. 

Steps to reproduce: Try to place any of the above mentioned gamemodes 

Misc: None

**Comment by forairan** [comment]
The issue was actually that the game would assign team colors, even in solo games. That said, this has been fixed, and will be deployed soon. As far as the CTF report, that's more of a feature request; we'll consider adding a slight "grace period", or waiting until everyone falls to the ground before allowing anyone to hit anyone else.

Thanks for the report!
