### ISSUE TITLE
Mask Bug

### ISSUE THREAD

**Issue by alpbaboy** [MCGamerNetwork/Issues#731]
When i type ./mask it showes this 
Regular,Iron,Gold,Diamond it cant be showed iron

**Comment by Jodemoted** [comment]
For Clarification - 
This happens Networkwide.
The issue is, when you use the /mask command, it displays a list of ranks that you can disguise as. 
If you attempt to do [/mask iron], it will automatically mask you as a regular player .
The bug here, I would presume, is that the iron rank is still displayed in the list, and should be removed.
![image](https://cloud.githubusercontent.com/assets/13568030/9023983/b3d1ab38-3868-11e5-9fc5-2e530c5fe6f6.png)
![image](https://cloud.githubusercontent.com/assets/13568030/9023984/b89e385c-3868-11e5-82e4-5ad51c650103.png)

**Comment by alpbaboy** [comment]
Ok thanks

**Comment by alpbaboy** [comment]
Ok thanks

**Comment by forairan** [comment]
As iron is no longer a rank, this option will be removed (as expected) in the next deployment cycle.
Thanks for the report!
