### ISSUE TITLE
1.7.10 always crashes when i play on this server. 

### ISSUE THREAD

**Issue by zachisbeast12** [MCGamerNetwork/Issues#837]
When I log on to the server and play survival games. I click a game and get in. Then about 5-10 minutes later I crash. Then when I play on 1.8 I'm always get lag spikes. So I cant really play. I please request that u try to fix this bug

**Comment by forairan** [comment]
Unfortunately, there's not much information to work off of here.
If you'd be able to give us more information (i.e. is your client crashing? What region? Date? Time? Server ID? Can you provide a copy of the crash report?), we'd be able to look into this issue further. Without that information (specifically, the crash report, if your client is crashing), trying to find the cause of the issue is like trying to find a needle in a haystack.

**Comment by zachisbeast12** [comment]
okay
