### ISSUE TITLE
Timing out on the website when signed into my account. 

### ISSUE THREAD

**Issue by Alb9n** [MCGamerNetwork/Issues#839]
Hello,
I don't remember the exact date, but earlier this year, during the summer, I was banned off the MCGamer forums for "abuse". I fully understand why I got banned and my ban expired within 3 days. The ban is not what the issue is about here. But whenever I am signed into my account (which is Ryska), I tend to time out more often than I should. I always get the same reply; 
"The server responded with an error. The error message is in the JavaScript console." (Can be seen here; http://prntscr.com/92po35 )
Either the website runs very slow, and eventually times me out, or either it just times me out immediately. 

This only happens when I am signed into my account Ryska, but if I am logged out completely or signed into another account, I never experience anything regarding this issue. 

I don't know if this is caused by the ban, but I am fairly confident that it is because of it. Please take a look into this and get back to me as soon as possible. 

Things to note;
My forum account: Ryska
Screenshot of error: http://prntscr.com/92po35

**Comment by arsenalfcgunners** [comment]
@Alb9n This is happens to me as well, and this is why it happens. (I believe)

If you are on the website for a long period of time without refreshing the page or going to a new page the CloudFlare DDOS protection is not able to verify that you are harmless.  Therefore, it cuts off your connection the the server until you refresh the page or go to a new page.  This is why when you go to do something on a page such as check your alerts you get that error.  refresh the page and the CloudFlare thing will come up for about 5 seconds and then you are good to go!

That is what I have noticed I could be wrong.  Don't think this has anything to do with your ban.  Probably only happens when you are logged in because you can't do things such as reply to a thread or check alerts unless you are logged in.
